# Generated by Django 5.0.7 on 2024-08-07 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_app', '0002_remove_garage_cars_garagedcar_garage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garagedcar',
            name='VIN',
            field=models.CharField(default='XXX-XXX-XXX-XXX', max_length=17),
        ),
        migrations.AlterField(
            model_name='garagedcar',
            name='make',
            field=models.CharField(default='Ford', max_length=100),
        ),
        migrations.AlterField(
            model_name='garagedcar',
            name='model',
            field=models.CharField(default='Mustang', max_length=100),
        ),
        migrations.AlterField(
            model_name='garagedcar',
            name='year',
            field=models.IntegerField(default=2017, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
