# Generated by Django 5.0.7 on 2024-08-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_app', '0003_alter_garagedcar_vin_alter_garagedcar_make_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garagedcar',
            name='services',
            field=models.TextField(default='list of services:'),
        ),
    ]
