# Generated by Django 5.0.7 on 2024-08-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_app', '0004_alter_garagedcar_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garagedcar',
            name='services',
            field=models.TextField(),
        ),
    ]
