# Generated by Django 5.0.7 on 2024-08-07 16:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bounty_filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)])),
                ('max_price', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bounty_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filters', models.ManyToManyField(to='bounty_list_app.bounty_filter')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bounty_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
