//IF A BAD URL PATH IS ENTERED THIS IS THE PAGE THAT IS RENDERED. THERE IS NO STYLING.
//THE HEADER WILL BE ADDED TO THE PAGE IN THE FUTURE TO ALLOW USERS TO NAVIGATE BACK TO REST OF THE APPLICATION
import React from 'react'

function NotFoundPage() {
  return (
    <h1>404 PAGE NOT FOUND</h1>
  )
}

export default NotFoundPage